version: '3'
services:

  vscsync:
    image: lolinternet/vscsync:latest
    build:
      context: ./
      dockerfile: ./vscoffline/vscsync/Dockerfile
    dns:
      - 1.1.1.1
    volumes:
      # Enable for dev
      # - ./vscoffline/:/opt/vscoffline/:ro
      - ./artifacts/:/artifacts/
      - ./logs/:/logs/
    environment:
      - SYNCARGS=--sync --total-recommended 1000 --logfile /logs/sync.log
